;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        eval-buffer
        kill-region
        magit-commit
        mark-sexp
        multiple-cursors-mode
        save-some-buffers
        ))

(setq mc/cmds-to-run-once
      '(
        end-of-buffer
        magit-copy-buffer-revision
        transient-quit-one
        ))
